version: '3'

services:
  app:
    container_name: mypage_app
    build: ./app
    working_dir: /home/docker/app
    command: > 
      /bin/bash -c "source ~/.bash_profile && \
                    python manage.py migrate && \
                    supervisord -n"
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=www.toshikiohnogi.net
      - LETSENCRYPT_HOST=www.toshikiohnogi.net

networks:
  default:
    external:
      name: webproxy
